#ifndef APPLE_IAP2_FID_H
#define APPLE_IAP2_FID_H

#include <support/apple/iap2.h>

typedef enum
{
	IAP2_FID_TOKEN_IDENTIFY = 0x00,
	IAP2_FID_TOKEN_ACCESORY_CAPS,
	IAP2_FID_TOKEN_ACCESORY_INFO,
	IAP2_FID_TOKEN_IPOD_PREFEERENCE,
	IAP2_FID_TOKEN_EA_PROTOCOL,
	IAP2_FID_TOKEN_BUNDLE_SEED_ID_PREF,
	IAP2_FID_TOKEN_EA_PROTOCOL_METADATA = 0x08,
	IAP2_FID_TOKEN_ACCESORY_DIGITAL_AUDIO_SAMPLE_RATES = 0x0E,
	IAP2_FID_TOKEN_ACCESORY_DIGITAL_AUDIO_VIDEO_DELAY,
} IAP2_FID_TOKEN;

typedef struct
{
	unsigned short Token;
	unsigned short DataLength;
	unsigned char *Data;
} IAP2_FID_TOKEN_VALUES;

#define IAP2_ACCESORY_CAPS_TOKENF_ANALOG_LINE_OUT (1<<0)
#define IAP2_ACCESORY_CAPS_TOKENF_ANALOG_LINE_IN (1<<1)
#define IAP2_ACCESORY_CAPS_TOKENF_ANALOG_VIDEO_OUT (1<<2)
#define IAP2_ACCESORY_CAPS_TOKENF_USB_AUDIO_OUT (1<<4)
#define IAP2_ACCESORY_CAPS_TOKENF_APPLICATION (1<<9)
#define IAP2_ACCESORY_CAPS_TOKENF_CHECKS_VOLUME (1<<11)
#define IAP2_ACCESORY_CAPS_TOKENF_USES_VOICE_OVER (1<<17)
#define IAP2_ACCESORY_CAPS_TOKENF_ASYNC_PLAYBACK_STATE (1<<18)
#define IAP2_ACCESORY_CAPS_TOKENF_HOST_AUDIO_VIDEO_SWITCH (1<<21)
#define IAP2_ACCESORY_CAPS_TOKENF_ASSISTIVE_TOUCH (1<<23)

typedef enum
{
	IAP2_ACCESORY_INFO_NAME = 0x01,
	IAP2_ACCESORY_INFO_FW_VERSION = 0x04,
	IAP2_ACCESORY_INFO_HW_VERSION = 0x05,
	IAP2_ACCESORY_INFO_MANUFACTURER = 0x06,
	IAP2_ACCESORY_INFO_MODEL = 0x07,
	IAP2_ACCESORY_INFO_SERIAL = 0x08,
	IAP2_ACCESORY_INFO_MAX_INCOMING_PAYLOAD = 0x09,
	IAP2_ACCESORY_INFO_STATUS = 0x0B,
	IAP2_ACCESORY_INFO_RF_CERTIFICATION = 0x0C,
} IAP2_ACCESORY_INFO_TYPE;

#define IAP2_ACCESORY_RF_CERT_CLASS1 (1<<0)
#define IAP2_ACCESORY_RF_CERT_CLASS2 (1<<1)
#define IAP2_ACCESORY_RF_CERT_CLASS3 (1<<2)
#define IAP2_ACCESORY_RF_CERT_CLASS4 (1<<3)
#define IAP2_ACCESORY_RF_CERT_CLASS5 (1<<4)
#define IAP2_ACCESORY_RF_CERT_CLASS6 (1<<5)
#define IAP2_ACCESORY_RF_CERT_CLASS7 (1<<6)

#define FID32(a) ((a) >> 24), ((a) >> 16), ((a) >> 8), (a)

// prototypes
int iap2_fid_fill(unsigned char *payload, int max_payload);


#endif // APPLE_IAP2_FID_H


