#ifndef NORDIC_ACI_H
#define NORDIC_ACI_H

#include <kernel/event.h>

typedef struct
{
	EXOS_NODE Node;
	unsigned char Command;
	unsigned char Length;
	unsigned char Data[32];
} ACI_REQUEST;

typedef enum
{
	ACI_EVENT_DEVICE_STARTED = 0x81,
	ACI_EVENT_ECHO = 0x82,
	ACI_EVENT_HW_ERROR = 0x83,
	ACI_EVENT_COMMAND_RESPONSE = 0x84,
	ACI_EVENT_CONNECTED = 0x85,
	ACI_EVENT_DISCONNECTED = 0x86,
	ACI_EVENT_BOND_STATUS = 0x87,
	ACI_EVENT_PIPE_STATUS = 0x88,
	ACI_EVENT_TIMING = 0x89,
	ACI_EVENT_DATA_CREDIT = 0x8A,
	ACI_EVENT_DATA_ACK = 0x8B,
	ACI_EVENT_DATA_RECEIVED = 0x8C,
	ACI_EVENT_PIPE_ERROR = 0x8D,
	ACI_EVENT_DISPLAY_KEY = 0x8E,
	ACI_EVENT_KEY_REQUEST = 0x8F,
} ACI_EVENT;

typedef enum
{
	ACI_BOND_STATUS_SUCCESS = 0,
	ACI_BOND_STATUS_FAILED = 0x01,
	ACI_BOND_STATUS_FAILED_TIMEOUT = 0x02,
	ACI_BOND_STATUS_FAILED_PASSKEY_ENTRY_FAILED = 0x81,
	ACI_BOND_STATUS_FAILED_OOB_UNAVAILABLE = 0x82,
	ACI_BOND_STATUS_FAILED_AUTHENTICATION_REQ = 0x83,
	ACI_BOND_STATUS_FAILED_CONFIRM_VALUE = 0x84,
	ACI_BOND_STATUS_FAILED_PAIRING_UNSUPPORTED = 0x85,
	ACI_BOND_STATUS_FAILED_ENCRYPTION_KEY_SIZE = 0x86,
	ACI_BOND_STATUS_FAILED_SMP_CMD_UNSUPPORTED = 0x87,
	ACI_BOND_STATUS_FAILED_UNSPECIFIED_REASON = 0x88,
	ACI_BOND_STATUS_FAILED_REPEATED_ATTEMPTS = 0x89,
	ACI_BOND_STATUS_FAILED_INVALID_PARAMETERS = 0x8A,
} ACI_BOND_STATUS;

typedef enum
{
	ACI_STATUS_SUCCESS = 0x00,
	ACI_STATUS_TRANSACTION_CONTINUE = 0x01,
	ACI_STATUS_TRANSACTION_COMPLETE = 0x02,
	ACI_STATUS_EXTENDED = 0x03,

	ACI_STATUS_ERROR_UNKNOWN = 0x80,
	ACI_STATUS_ERROR_INTERNAL = 0x81,
	ACI_STATUS_ERROR_CMD_UNKNOWN = 0x82,
	ACI_STATUS_ERROR_DEVICE_STATE_INVALID = 0x83,
	ACI_STATUS_ERROR_INVALID_LENGTH = 0x84,
	ACI_STATUS_ERROR_INVALID_PARAMETER = 0x85,
	ACI_STATUS_ERROR_BUSY = 0x86,
	ACI_STATUS_ERROR_INVALID_DATA = 0x87,
	ACI_STATUS_ERROR_CRC_MISMATCH = 0x88,
	ACI_STATUS_ERROR_UNSUPPORTED_SETUP_FORMAT = 0x89,
	ACI_STATUS_ERROR_INVALID_SEQ_NO = 0x8A,
	ACI_STATUS_ERROR_SETUP_LOCKED = 0x8B,
	ACI_STATUS_ERROR_LOCK_FAILED = 0x8C,
	ACI_STATUS_ERROR_BOND_REQUIRED = 0x8D,
	ACI_STATUS_ERROR_REJECTED = 0x8E,
	ACI_STATUS_ERROR_DATA_SIZE = 0x8F,
	ACI_STATUS_ERROR_PIPE_INVALID = 0x90,
	ACI_STATUS_ERROR_CREDIT_NOT_AVAILABLE = 0x91,
	ACI_STATUS_ERROR_PEER_ATT_ERROR = 0x92,
	ACI_STATUS_ERROR_ADVT_TIMEOUT = 0x93,
	ACI_STATUS_ERROR_PEER_SMP_ERROR = 0x94,
	ACI_STATUS_ERROR_PIPE_TYPE_INVALID = 0x95,
	ACI_STATUS_ERROR_PIPE_STATE_INVALID = 0x96,
	ACI_STATUS_ERROR_INVALID_KEY_SIZE = 0x97,
	ACI_STATUS_ERROR_INVALID_KEY_DATA = 0x98,
} ACI_STATUS_CODE;

void aci_initialize();

#endif // NORDIC_ACI_H


