// Exos glue code for use of nrfgo service headers
// This header is included in service headers generated by nrfgo and
// needs to define std int and bool types
// Miguel Fides @ MIO Research Labs

#ifndef NRFGO_HAL_PLATFORM_H__
#define NRFGO_HAL_PLATFORM_H__

#include <stdint.h>
#include <stdbool.h>

#endif /* NRFGO_HAL_PLATFORM_H__ */
