#ifndef XBMS_H
#define XBMS_H

typedef enum
{
	XBMS_STATE_OFF = 0,
	XBMS_STATE_ON,
	XBMS_STATE_CHARGE,
	XBMS_STATE_CHARGE_BALANCE,
	XBMS_STATE_CHARGE_FULL,
	XBMS_STATE_FULL_BALANCE,
} XBMS_STATE;

typedef enum
{
	XBMS_STATUS_IDLE = 0,
	XBMS_STATUS_CHARGER_PRESENT = (1<<0),
	XBMS_STATUS_FULL = (1<<1),
	XBMS_STATUS_LOADED = (1<<2),
	XBMS_STATUS_LOW_BATTERY = (1<<3),
	XBMS_STATUS_ERROR = (1<<4),
	XBMS_STATUS_VIN_SENSE_MISMATCH = (1<<5),
	XBMS_STATUS_SUPERVISOR_FAILURE = (1<<6),
} XBMS_STATUS;

#endif // XBMS_H


