#ifndef EXOS_NET_PPP_LCP_H
#define EXOS_NET_PPP_LCP_H

#include <modules/net/ppp/ppp.h>

typedef enum
{
	LCP_CONFIGURE_REQUEST = 1,
	LCP_CONFIGURE_ACK = 2,
	LCP_CONFIGURE_NAK = 3,
	LCP_CONFIGURE_REJECT = 4,
	LCP_TERMINATE_REQUEST = 5,
	LCP_TERMINATE_ACK = 6,
	LCP_CODE_REJECT = 7,
	LCP_PROTOCOL_REJECT = 8,
	LCP_ECHO_REQUEST = 9,
	LCP_ECHO_REPLY = 10,
	LCP_DISCARD_REQUEST = 11,
} LCP_CODE;

typedef enum
{
	LCP_OPTION_RESERVED = 0,
	LCP_OPTION_MRU = 1,
	LCP_OPTION_AUTHENTICATION_PROTOCOL = 3,
	LCP_OPTION_QUALITY_PROTOCOL = 4,
	LCP_OPTION_MAGIC_NUMBER = 5,
	LCP_OPTION_PROTOCOL_FIELD_COMPRESSION = 7,
	LCP_OPTION_ADDRESS_AND_CONTROL_FIELD_COMPRESSION = 8,
} LCP_OPTION_TYPE;


void ppp_lcp_parse(PPP_CONTEXT *context, unsigned char *buffer, int length);

#endif // EXOS_NET_PPP_LCP_H

