#ifndef USB_HUB_H
#define USB_HUB_H

#include <usb/usb.h>

typedef struct __attribute__((__packed__))
{
	USB_DESCRIPTOR_HEADER Header;
	unsigned char NbrPorts;
	USB16 HubCharacteristics;
	unsigned char PwrOn2PwrGood;
	unsigned char DeviceRemovable;
} USB_HUB_DESCRIPTOR;

#define USB_HUB_DESCRIPTOR_HUB 0x29

typedef enum
{
	USB_HUB_FEATURE_C_HUB_LOCAL_POWER = 0,
	USB_HUB_FEATURE_C_HUB_OVER_CURRENT,
	USB_HUB_FEATURE_PORT_CONNECTION = 0,
	USB_HUB_FEATURE_PORT_ENABLE,
	USB_HUB_FEATURE_PORT_SUSPEND,
	USB_HUB_FEATURE_PORT_OVER_CURRENT,
	USB_HUB_FEATURE_PORT_RESET,
	USB_HUB_FEATURE_PORT_POWER = 8,
	USB_HUB_FEATURE_PORT_LOW_SPEED,
	USB_HUB_FEATURE_C_PORT_CONNECTION = 16,
	USB_HUB_FEATURE_C_PORT_ENABLE,
	USB_HUB_FEATURE_C_PORT_SUSPEND,
	USB_HUB_FEATURE_C_PORT_OVER_CURRENT,
	USB_HUB_FEATURE_C_PORT_RESET,
	USB_HUB_FEATURE_PORT_TEST,
	USB_HUB_FEATURE_PORT_INDICATOR,
} USB_HUB_FEATURE;

#define USB_HUBF_PORT_CONNECTION (1<<0)
#define USB_HUBF_PORT_ENABLE (1<<1)
#define USB_HUBF_PORT_SUSPEND (1<<2)
#define USB_HUBF_PORT_OVER_CURRENT (1<<3)
#define USB_HUBF_PORT_RESET (1<<4)
#define USB_HUBF_PORT_POWER (1<<8)
#define USB_HUBF_PORT_LOW_SPEED (1<<9)
#define USB_HUBF_PORT_HIGH_SPEED (1<<10)
#define USB_HUBF_PORT_TEST (1<<11)
#define USB_HUBF_PORT_INDICATOR (1<<12)

#endif // USB_HUB_H



